spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:vietshirt_db}
    username: ${DB_USERNAME:vietshirt}
    password: ${DB_PASSWORD:vietshirt_password}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

  task:
    execution:
      pool:
        core-size: 5
        max-size: 10
        queue-capacity: 25
      thread-name-prefix: mosiac-async-

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
#            redirect-uri: ${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}
            redirect-uri: ${GOOGLE_REDIRECT_URI:http://ec2-54-169-96-88.ap-southeast-1.compute.amazonaws.com/login/oauth2/code/google}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# Storage configuration
storage:
  type: ${STORAGE_TYPE:minio}

# MinIO configuration
minio:
  endpoint: ${MINIO_ENDPOINT:localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minio_user}
  secret-key: ${MINIO_SECRET_KEY:minio_password}
  bucket: ${MINIO_BUCKET:mosaic}
  secure: ${MINIO_SECURE:false}

# AWS S3 configuration
aws:
  s3:
    region: ${AWS_REGION:ap-southeast-1}
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    bucket: ${AWS_S3_BUCKET:khoas3bucket}

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${JWT_EXPIRATION:86400000}
      refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}
  front-end-url: ${FRONTEND_URL:https://mosiacstore.vercel.app}

vnpay:
  version: ${VNPAY_VERSION:2.1.0}
  tmnCode: ${VNPAY_TMN_CODE}
  hashSecret: ${VNPAY_HASH_SECRET}
  paymentUrl: ${VNPAY_PAYMENT_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
  returnUrl: ${VNPAY_RETURN_URL:http://ec2-54-169-96-88.ap-southeast-1.compute.amazonaws.com/api/v1/payment/vnpay/payment-callback}
  apiUrl: ${VNPAY_API_URL:https://sandbox.vnpayment.vn/merchant_webapi/api/transaction}

#Actuator configurations
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always



